export MAIN_BRANCH='main'

alias hbo='export MAIN_BRANCH="master"'
alias wbd='export MAIN_BRANCH="main"'

# ===========
# GIT ALIASES
# ===========
alias br='git branch --list'
alias cbr='git checkout -b'
alias cl='gcm; pu; gp; grpo; dbr -D'
alias dbr='git branch -d'
alias diffmd='git log upstream/$MAIN_BRANCH..develop'
alias g='git'
alias gca='git commit --amend'
alias gcb='git commit -m "`git branch --show-current`"'
alias gcd='git checkout develop'
alias gcm='git checkout $MAIN_BRANCH'
alias gcr='git commit -eF .git/COMMIT_EDITMSG'
alias gl='git log --oneline'
alias gp='git push origin'
alias gpl='git pull --rebase'
alias gpo='git push origin `git branch --show-current`'
alias grc='git rebase --continue'
alias grd='git rebase develop'
alias grm='git rebase $MAIN_BRANCH'
alias grpo='git remote prune origin'
alias gs='git status'
alias gsh='git show --pretty="" --name-status'
alias gsha='git rev-parse HEAD'
alias plr='git pull --rebase'
alias plud='git pull --rebase upstream develop'
alias plum='git pull --rebase upstream $MAIN_BRANCH'
alias pu='plum'
alias rnbr='git branch -m'
alias sub='git submodule update --recursive --init'
